version: '3.8'

services:
  # Databases
  mongodb:
    image: mongo:7
    container_name: emorobcare-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: emorobcare
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    container_name: emorobcare-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  fuseki:
    image: stain/jena-fuseki:latest
    container_name: emorobcare-fuseki
    ports:
      - "3030:3030"
    volumes:
      - fuseki_data:/fuseki
    environment:
      FUSEKI_BASEDATASET: /fuseki/databases/emorobcare
    command: ["--update", "--mem", "/datasets"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$$/stats"]
      interval: 30s
      timeout: 10s
      retries: 5

  # LLM Service (vLLM - Separate GPU Service)
  vllm:
    image: vllm/vllm-openai:latest
    container_name: emorobcare-vllm
    ports:
      - "8001:8000"
    environment:
      # vLLM Configuration
      VLLM_HOST: "0.0.0.0"
      VLLM_PORT: "8000"
      VLLM_TRUST_REMOTE_CODE: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: 
      - "--model"
      - "Qwen/Qwen2-7B-Instruct"
      - "--gpu-memory-utilization"
      - "0.6"
      - "--max-model-len"
      - "4096"
      - "--dtype"
      - "auto"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 120s

  # Application Services
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: emorobcare-api
    ports:
      - "8000:8000"
    environment:
      # Database connections
      MONGODB_URI: mongodb://mongodb:27017
      QDRANT_URL: http://qdrant:6333
      FUSEKI_URL: http://fuseki:3030
      # vLLM API connection (CRITICAL: HTTP client, not import)
      VLLM_API_URL: http://vllm:8000
      LLM_MODEL: Qwen/Qwen2-7B-Instruct
      # Configuration
      OFFLINE_MODE: "true"
      DEFAULT_LANG: "es"
      ASR_GPU: "false"
      # Memory configuration
      EMBEDDING_ENABLE_SEMANTIC_SEARCH: "true"
      SEMANTIC_SEARCH_LIMIT: "5"
      CONTEXT_RETRIEVAL_LIMIT: "3"
    depends_on:
      vllm:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      fuseki:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  asr:
    build:
      context: .
      dockerfile: services/asr/Dockerfile
    container_name: emorobcare-asr
    ports:
      - "5000:5000"
    environment:
      DEFAULT_LANGUAGE: "es"
      GPU_ENABLED: "false"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: emorobcare-frontend
    ports:
      - "81:80"
    environment:
      API_URL: http://localhost:8000
      ASR_URL: http://localhost:5000
    depends_on:
      api:
        condition: service_healthy
      asr:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Knowledge Graph Service
  fuseki-job:
    build:
      context: .
      dockerfile: services/fuseki-job/Dockerfile
    container_name: emorobcare-fuseki-job
    environment:
      FUSEKI_URL: http://fuseki:3030
      DATASET: emorobcare
    depends_on:
      fuseki:
        condition: service_healthy
    volumes:
      - ./scripts:/app/scripts
    restart: "no"
    command: ["--action", "init"]

volumes:
  mongodb_data:
    driver: local
  qdrant_data:
    driver: local
  fuseki_data:
    driver: local

networks:
  default:
    name: emorobcare-network
    driver: bridge